"""add customer to ticket drafts

Revision ID: 760c398d6a75
Revises: b32ac7fe7fe3
Create Date: 2026-09-28 13:32:44.043412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760c398d6a75'
down_revision: Union[str, Sequence[str], None] = 'b32ac7fe7fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_ticket_drafts', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pending_ticket_drafts', 'users', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'pending_ticket_drafts', type_='foreignkey')
    op.drop_column('pending_ticket_drafts', 'customer_id')
    # ### end Alembic commands ###
