"""add pending ticket drafts

Revision ID: b32ac7fe7fe3
Revises: c7f092bd6ad3
Create Date: 2026-09-28 13:01:10.850629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32ac7fe7fe3'
down_revision: Union[str, Sequence[str], None] = 'c7f092bd6ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_ticket_drafts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tickets', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_ticket_drafts')
    # ### end Alembic commands ###
